# Generated by Django 3.1.7 on 2021-09-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immagineprofilo',
            name='immagine',
            field=models.ImageField(upload_to='user/img/%Y-%m-%d/'),
        ),
    ]
