# Generated by Django 3.1.7 on 2021-09-13 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profile_picture.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_picture', '0002_auto_20210913_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='immagineprofilo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='immagineprofilo',
            name='immagine',
            field=models.ImageField(upload_to=profile_picture.models.upload_to),
        ),
        migrations.AlterUniqueTogether(
            name='immagineprofilo',
            unique_together={('user', 'immagine')},
        ),
        migrations.RemoveField(
            model_name='immagineprofilo',
            name='utente',
        ),
    ]
