# Generated by Django 3.1.7 on 2021-09-13 18:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_picture', '0003_auto_20210913_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immagineprofilo',
            old_name='immagine',
            new_name='profile_picture',
        ),
        migrations.AlterUniqueTogether(
            name='immagineprofilo',
            unique_together={('user', 'profile_picture')},
        ),
    ]
