# Generated by Django 3.1.7 on 2021-07-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210717_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tavolo',
            options={'verbose_name_plural': 'Tavoli'},
        ),
    ]
