# Generated by Django 3.1.7 on 2021-07-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210721_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='tavolo',
        ),
        migrations.RemoveField(
            model_name='tavolo',
            name='id',
        ),
        migrations.AlterField(
            model_name='tavolo',
            name='nome',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
