# Generated by Django 3.1.7 on 2021-07-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_prenotazione_tavolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tavolo',
            name='stato',
            field=models.CharField(choices=[('A', 'Abilitato'), ('D', 'Disabilitato')], default='A', max_length=1),
        ),
    ]
