# Generated by Django 3.1.7 on 2021-07-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210721_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prenotazione',
            options={'verbose_name_plural': 'Prenotazioni'},
        ),
    ]
