# Generated by Django 3.1.7 on 2021-07-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_prenotazione_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tavolo',
            name='stato',
        ),
        migrations.AddField(
            model_name='tavolo',
            name='abilitato',
            field=models.BooleanField(default=True, verbose_name='Abilitato'),
        ),
    ]
