# Generated by Django 3.1.7 on 2021-07-22 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0009_auto_20210722_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together={('data_ora', 'tavolo', 'utente')},
        ),
    ]
