# Generated by Django 3.1.7 on 2021-07-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20210722_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='queue_place',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
