# Generated by Django 3.1.7 on 2021-07-22 22:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0011_prenotazione_queue_place'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together={('data_ora', 'tavolo', 'utente', 'queue_place')},
        ),
    ]
