# Generated by Django 3.1.7 on 2021-07-23 00:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0013_auto_20210723_0036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together={('data_ora', 'tavolo', 'utente', 'queue_place'), ('data_ora', 'utente'), ('data_ora', 'tavolo', 'queue_place')},
        ),
    ]
