# Generated by Django 3.1.7 on 2021-07-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20210723_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='queue_place',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
