# Generated by Django 3.1.7 on 2021-09-10 20:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0015_auto_20210723_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='queue_place',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='tavolo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.tavolo'),
        ),
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together={('data_ora', 'tavolo', 'utente'), ('data_ora', 'utente', 'queue_place')},
        ),
    ]
