# Generated by Django 3.1.7 on 2021-09-10 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20210910_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='queue_place',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
