# Generated by Django 3.1.7 on 2021-09-10 21:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0018_auto_20210910_2255'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together={('data_ora', 'utente'), ('data_ora', 'queue_place')},
        ),
    ]
