# Generated by Django 3.1.7 on 2021-09-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20210914_2106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together={('data_ora', 'tavolo', 'queue_place'), ('data_ora', 'tavolo')},
        ),
    ]
