# Generated by Django 3.1.7 on 2021-09-15 16:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20210915_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='queue_place',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='tavolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.tavolo'),
        ),
    ]
