# Generated by Django 3.1.7 on 2021-09-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20210915_1819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together={('data_ora', 'queue_place'), ('data_ora', 'tavolo')},
        ),
    ]
