# Generated by Django 3.1.7 on 2021-09-15 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0023_auto_20210915_1820'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together={('data_ora', 'tavolo'), ('data_ora', 'queue_place'), ('data_ora', 'utente')},
        ),
    ]
