# Generated by Django 3.1.7 on 2021-09-16 20:53

from django.db import migrations, models
import foto_ricordo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoRicordo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_ricordo', models.ImageField(upload_to=foto_ricordo.models.upload_to)),
                ('data_ora', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Foto Ricordo',
            },
        ),
    ]
