# Generated by Django 3.1.7 on 2021-09-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foto_ricordo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotoricordo',
            old_name='data_ora',
            new_name='data',
        ),
    ]
