# Generated by Django 3.1.7 on 2021-07-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210721_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piatto',
            name='descrizione',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
